name: chapter22

ghc-options: -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates

source-dirs: test
dependencies:
  - base
  - QuickCheck
  - hspec

library:
  source-dirs: src
  dependencies:
    - base

tests:
  exercise-ask:
    main: exercise-ask.hs

  exercise-reading-comprehension:
    main: exercise-reading-comprehension.hs

  exercise-warming-up:
    main: exercise-warming-up.hs
