resolver: lts-8.11

packages:
  - ./15-monoid-semigroup
  - ./16-functor
  - ./17-applicative
  - ./18-monad
  - ./20-foldable
  - ./21-traversable
  - ./22-reader

extra-deps: []

flags: {}

extra-package-dbs: []
