name: chapter23

ghc-options: -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates

source-dirs: test
dependencies:
  - QuickCheck
  - base
  - hspec
  - random
  - transformers

library:
  source-dirs: src
  dependencies:
    - base
    - random
    - transformers

tests:
  exercise-roll-your-own:
    main: exercise-roll-your-own.hs
    dependencies:
      - chapter23
