name: chapter20

ghc-options: -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates
source-dirs: test
dependencies:
  - base
  - QuickCheck
  - checkers
  - hspec
  - hspec-checkers

tests:
  exercise-library-functions:
    main: exercise-library-functions.hs

  exercises-chapter:
    main: exercises-chapter.hs
