name: chapter18

ghc-options: -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates
source-dirs: test
dependencies:
  - base
  - QuickCheck
  - checkers
  - hspec
  - hspec-checkers

library:
  source-dirs: src
  dependencies:
    - base

tests:
  bind-from-join:
    main: bind-from-join.hs

  exercise-either:
    main: exercise-either.hs

  exercises-chapter:
    main: exercises-chapter.hs
