name: chapter21

ghc-options: -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates
source-dirs: test
dependencies:
  - base
  - QuickCheck
  - checkers
  - hspec
  - hspec-checkers

library:
  source-dirs: src
  dependencies:
    - base
    - bytestring
    - containers
    - wreq

tests:
  exercises-chapter:
    main: exercises-chapter.hs
